# Site settings
title: jeffgabhart.github.io
email: lazydesert@gmail.com
description: "Perhaps you'll find this useful."
baseurl: ""
url: "http://jeffgabhart.github.io"

# Build settings
markdown: kramdown
permalink: pretty
