# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jeff Gabhart
tagline:          'Maybe this is useful to you'
description:      ''
url:              http://jeffgabhart.github.io

author:
  name:           'Jeff Gabhart'
  url:            https://twitter.com/jeffgabhart

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           
