# Site settings
title: "Jeff Gabhart"
email: lazydesert@gmail.com
username: jeffgabhart
description: "Perhaps you'll find this useful."
baseurl: ""
url: "http://jeffgabhart.github.io"

# Build settings
markdown: kramdown
permalink: pretty
