# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jeff Gabhart
tagline:          ''
description:      'Maybe this will help.'
url:              http://jeffgabhart.github.io

author:
  name:           'Jeff Gabhart'
  url:            https://twitter.com/jeffgabhart

paginate:         5

# Custom vars
